class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror3'
        self.UnzipMirrorCommand = 'unzipmirror3'
        self.TarMirrorCommand = 'tarmirror3'
        self.ZipMirrorCommand = 'zipmirror3'
        self.CancelMirror = 'cancel3'
        self.CancelAllCommand = 'cancelall3'
        self.ListCommand = 'search'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest3'
        self.CloneCommand = 'clone3'
        self.CountCommand = 'count3'
        self.WatchCommand = 'watch3'
        self.TarWatchCommand = 'tarwatch3'
        self.DeleteCommand = 'del3'
        self.ShellCommand = 'shell3'
        self.ExecHelpCommand = 'exechelp'
        self.TsHelpCommand = 'tshelp'

BotCommands = _BotCommands()
